import {css} from 'lit-element';

export const nuevabatallastyles=css`
*{
    box-sizing:border-box;
    margin:0;
    padding:0;
}
#contenido-seleccion{
   margin:8px;
   display:flex;
   flex-direction:column;
   height:100%; 
   width:100%

}
#container-batalla-ganador{
   border:ridge;
   display:flex;
   flex-direction:column;
   height:70%;
   width:100%;
}
#container-titulo{
   margin:5px;
   display:flex;
   justify-content:center;
   height:20%;
}
#container-ganador-img-p{
   display:flex;
   flex-direction:row;
  justify-content:space-around;
   width:100%;
   height:100%;
}
#container-img-ganador{
   margin:5px;
   border:ridge;
   display:flex;
   border-radius:1em;
   width:35%;
   height:30%;
}
#img-ganador{
width:100%;
height:100%;
}
#container-p-ganador{
   display:flex;
   align-items:center;
   width:60%;
}
#p-ganador{
   width:100%;
   text-align:center;
}
#container-boton-batalla-nueva{
   padding:8px;
   display:flex;
   justify-content:center;
   width:95%;
   height:30%;
}
#boton-batalla-nueva{
   width:95%;
}
`;